app:
  env: testing
  addr: "127.0.0.1:3000"
  application_name: "SOLSniffer"
  log:
   log_level: "trace"
   pretty_print: true

database:
  uri: "mongodb://localhost:27017"
  retry:
    attempts: 3
    delay: 2s
    delay_type: backoff

websocket:
  scheme: "ws"
  host: "localhost"
  path: "/ws"
  retry:
    attempts: 5
    delay: 1s
    delay_type: fixed

services:
  wallets:
    - "wallet1"
    - "wallet2"
  tokens:
    - "token1"
    - "token2"

coordinator:
  retry:
    attempts: 3
    delay: 2s
    delay_type: backoff

backfill:
  max_concurrency: 10
  chunk_size: 100
